services:
  factorio_0:
    command: /opt/factorio/bin/x64/factorio --start-server-load-scenario default_lab_scenario
      --port 34197 --server-settings /opt/factorio/config/server-settings.json --map-gen-settings
      /opt/factorio/config/map-gen-settings.json --map-settings /opt/factorio/config/map-settings.json
      --server-banlist /opt/factorio/config/server-banlist.json --rcon-port 27015
      --rcon-password "factorio" --server-whitelist /opt/factorio/config/server-whitelist.json
      --use-server-whitelist --server-adminlist /opt/factorio/config/server-adminlist.json
      --mod-directory /opt/factorio/mods
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
    entrypoint: []
    environment:
    - SAVES=/opt/factorio/saves
    - CONFIG=/opt/factorio/config
    - MODS=/opt/factorio/mods
    - SCENARIOS=/opt/factorio/scenarios
    - PORT=34197
    - RCON_PORT=27015
    image: factorio:latest
    platform: linux/amd64
    ports:
    - 34197:34197/udp
    - 27015:27015/tcp
    restart: unless-stopped
    user: factorio
    volumes:
    - source: ../scenarios/default_lab_scenario
      target: /opt/factorio/scenarios/default_lab_scenario
      type: bind
    - source: ~/Applications/Factorio.app/Contents/Resources/mods
      target: /opt/factorio/mods
      type: bind
  factorio_1:
    command: /opt/factorio/bin/x64/factorio --start-server-load-scenario default_lab_scenario
      --port 34197 --server-settings /opt/factorio/config/server-settings.json --map-gen-settings
      /opt/factorio/config/map-gen-settings.json --map-settings /opt/factorio/config/map-settings.json
      --server-banlist /opt/factorio/config/server-banlist.json --rcon-port 27015
      --rcon-password "factorio" --server-whitelist /opt/factorio/config/server-whitelist.json
      --use-server-whitelist --server-adminlist /opt/factorio/config/server-adminlist.json
      --mod-directory /opt/factorio/mods
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
    entrypoint: []
    environment:
    - SAVES=/opt/factorio/saves
    - CONFIG=/opt/factorio/config
    - MODS=/opt/factorio/mods
    - SCENARIOS=/opt/factorio/scenarios
    - PORT=34197
    - RCON_PORT=27015
    image: factorio:latest
    platform: linux/amd64
    ports:
    - 34198:34197/udp
    - 27016:27015/tcp
    restart: unless-stopped
    user: factorio
    volumes:
    - source: ../scenarios/default_lab_scenario
      target: /opt/factorio/scenarios/default_lab_scenario
      type: bind
    - source: ~/Applications/Factorio.app/Contents/Resources/mods
      target: /opt/factorio/mods
      type: bind
  factorio_2:
    command: /opt/factorio/bin/x64/factorio --start-server-load-scenario default_lab_scenario
      --port 34197 --server-settings /opt/factorio/config/server-settings.json --map-gen-settings
      /opt/factorio/config/map-gen-settings.json --map-settings /opt/factorio/config/map-settings.json
      --server-banlist /opt/factorio/config/server-banlist.json --rcon-port 27015
      --rcon-password "factorio" --server-whitelist /opt/factorio/config/server-whitelist.json
      --use-server-whitelist --server-adminlist /opt/factorio/config/server-adminlist.json
      --mod-directory /opt/factorio/mods
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
    entrypoint: []
    environment:
    - SAVES=/opt/factorio/saves
    - CONFIG=/opt/factorio/config
    - MODS=/opt/factorio/mods
    - SCENARIOS=/opt/factorio/scenarios
    - PORT=34197
    - RCON_PORT=27015
    image: factorio:latest
    platform: linux/amd64
    ports:
    - 34199:34197/udp
    - 27017:27015/tcp
    restart: unless-stopped
    user: factorio
    volumes:
    - source: ../scenarios/default_lab_scenario
      target: /opt/factorio/scenarios/default_lab_scenario
      type: bind
    - source: ~/Applications/Factorio.app/Contents/Resources/mods
      target: /opt/factorio/mods
      type: bind
  factorio_3:
    command: /opt/factorio/bin/x64/factorio --start-server-load-scenario default_lab_scenario
      --port 34197 --server-settings /opt/factorio/config/server-settings.json --map-gen-settings
      /opt/factorio/config/map-gen-settings.json --map-settings /opt/factorio/config/map-settings.json
      --server-banlist /opt/factorio/config/server-banlist.json --rcon-port 27015
      --rcon-password "factorio" --server-whitelist /opt/factorio/config/server-whitelist.json
      --use-server-whitelist --server-adminlist /opt/factorio/config/server-adminlist.json
      --mod-directory /opt/factorio/mods
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
    entrypoint: []
    environment:
    - SAVES=/opt/factorio/saves
    - CONFIG=/opt/factorio/config
    - MODS=/opt/factorio/mods
    - SCENARIOS=/opt/factorio/scenarios
    - PORT=34197
    - RCON_PORT=27015
    image: factorio:latest
    platform: linux/amd64
    ports:
    - 34200:34197/udp
    - 27018:27015/tcp
    restart: unless-stopped
    user: factorio
    volumes:
    - source: ../scenarios/default_lab_scenario
      target: /opt/factorio/scenarios/default_lab_scenario
      type: bind
    - source: ~/Applications/Factorio.app/Contents/Resources/mods
      target: /opt/factorio/mods
      type: bind
